# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3175607e4afd0cd95511c29fb593ed08eaa759b958649797d3df8edc41c76829b065d838ee0eb4a54d5749b2c38f13564c228a7e43b12043868e49be3568b0bd

test:
  secret_key_base: a09a57a9df0d02e5eccf85f1243722aae74cf6bdb61d0577d6a16afed46e25faec203829ca9a072c30a36c41976520fb9dd84f99daff883dbb614792846077b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
